"""Refresh the existing HAL bibliography, validating before atomic replacement."""
import os
from pathlib import Path
import re
import subprocess
import tempfile
import time
import urllib.error
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
STRUCTURE_IDS = ["1124151", "246190", "454685"]
URL = ('https://api.archives-ouvertes.fr/search/?q=structId_i:('
       + '%20OR%20'.join(STRUCTURE_IDS) + ')&wt=bibtex&start=0&rows=5000')
MAX_BYTES = 20 * 1024 * 1024


def download():
    for attempt in range(3):
        try:
            with urllib.request.urlopen(URL, timeout=30) as response:
                if response.status != 200:
                    raise ValueError('HAL returned an unexpected status')
                body = response.read(MAX_BYTES + 1)
            if len(body) > MAX_BYTES:
                raise ValueError('HAL response exceeds the size limit')
            return body.decode('utf-8-sig')
        except (urllib.error.URLError, TimeoutError):
            if attempt == 2:
                raise
            time.sleep(attempt + 1)


def clean_bibtex(text):
    # Preserve the existing keyword and PDF normalization rules.
    lines = text.split('\n')
    for i, line in enumerate(lines):
        match = re.search(r'^([ \t]*keywords[ \t]*=[ \t]*\{)(.*)(\},)$',
                          line, re.IGNORECASE)
        if match:
            keywords = [k.strip().strip('.-_!?').replace(',', '')
                        for k in match[2].split(';')]
            lines[i] = match[1] + ' , '.join(keywords) + match[3]
    for i, line in enumerate(lines):
        match = re.search(r'^([ \t]*PDF[ \t]*=[ \t]*\{https://.*\.?hal\.science/.*)/file/(.*).pdf(\},)$',
                          line, re.IGNORECASE)
        if match:
            lines[i] = match[1] + '/document' + match[3]
    header = ('% DO NOT EDIT THE FILE MANUALLY\n'
              '% This file is automatically generated by scripts/publication-update.sh\n'
              '% Any changes might be overwritten anytime\n\n\n')
    return header + '\n'.join(lines) + '\n'


def refresh(destination=ROOT / '_bibliography/rits-astra.bib'):
    text = download()
    candidate = None
    try:
        # Same filesystem as the destination: os.replace is atomic.
        with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', suffix='.bib',
                                         dir=destination.parent, delete=False) as stream:
            candidate = Path(stream.name)
            stream.write(clean_bibtex(text))
            stream.flush()
            os.fsync(stream.fileno())
        subprocess.run(['bundle', 'exec', 'ruby',
                        str(ROOT / 'scripts/validate_bibliography.rb'),
                        str(candidate), str(destination)], cwd=ROOT, check=True, timeout=60)
        candidate.chmod(0o644)
        os.replace(candidate, destination)
        print('HAL bibliography validated and replaced successfully.')
    finally:
        if candidate is not None and candidate.exists():
            candidate.unlink()


if __name__ == '__main__':
    try:
        refresh()
    except Exception:
        # Do not print response bodies, credentials, or partially parsed data.
        raise SystemExit('HAL update failed; existing bibliography preserved.')
