"""Refresh the existing HAL bibliography, validating before atomic replacement."""
import os
from pathlib import Path
import re
import socket
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
STRUCTURE_IDS = ["1124151", "246190", "454685"]
URL = ('https://api.archives-ouvertes.fr/search/?q=structId_i:('
       + '%20OR%20'.join(STRUCTURE_IDS) + ')&wt=bibtex&start=0&rows=5000')
MAX_BYTES = 20 * 1024 * 1024
REMOTE_FAILURE = 75  # Reserved for the shell wrapper's validated fallback policy.


class RemoteFetchError(Exception):
    """No usable response was obtained from the remote service."""


def download():
    for attempt in range(3):
        try:
            with urllib.request.urlopen(URL, timeout=30) as response:
                if response.status != 200:
                    raise urllib.error.URLError('HAL returned an unexpected status')
                body = response.read(MAX_BYTES + 1)
                expected_length = response.getheader('Content-Length')
        except (urllib.error.URLError, TimeoutError, ConnectionError, socket.gaierror) as error:
            if attempt == 2:
                raise RemoteFetchError('HAL remote fetch unavailable') from error
            time.sleep(attempt + 1)
            continue
        # Received but invalid/truncated content is a hard failure, not fallback.
        if len(body) > MAX_BYTES:
            raise ValueError('HAL response exceeds the size limit')
        if expected_length is not None and len(body) != int(expected_length):
            raise ValueError('HAL response is incomplete')
        return body.decode('utf-8-sig')


def clean_bibtex(text):
    # Preserve the existing keyword and PDF normalization rules.
    lines = text.split('\n')
    for i, line in enumerate(lines):
        match = re.search(r'^([ \t]*keywords[ \t]*=[ \t]*\{)(.*)(\},)$',
                          line, re.IGNORECASE)
        if match:
            keywords = [k.strip().strip('.-_!?').replace(',', '')
                        for k in match[2].split(';')]
            lines[i] = match[1] + ' , '.join(keywords) + match[3]
    for i, line in enumerate(lines):
        match = re.search(r'^([ \t]*PDF[ \t]*=[ \t]*\{https://.*\.?hal\.science/.*)/file/(.*).pdf(\},)$',
                          line, re.IGNORECASE)
        if match:
            lines[i] = match[1] + '/document' + match[3]
    header = ('% DO NOT EDIT THE FILE MANUALLY\n'
              '% This file is automatically generated by scripts/publication-update.sh\n'
              '% Any changes might be overwritten anytime\n\n\n')
    return header + '\n'.join(lines) + '\n'


def refresh(destination=ROOT / '_bibliography/rits-astra.bib'):
    text = download()
    candidate = None
    try:
        # Same filesystem as the destination: os.replace is atomic.
        with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', suffix='.bib',
                                         dir=destination.parent, delete=False) as stream:
            candidate = Path(stream.name)
            stream.write(clean_bibtex(text))
            stream.flush()
            os.fsync(stream.fileno())
        subprocess.run(['bundle', 'exec', 'ruby',
                        str(ROOT / 'scripts/validate_bibliography.rb'),
                        str(candidate), str(destination)], cwd=ROOT, check=True, timeout=60)
        candidate.chmod(0o644)
        os.replace(candidate, destination)
        print('HAL bibliography validated and replaced successfully.')
    finally:
        if candidate is not None and candidate.exists():
            candidate.unlink()


def main(destination=ROOT / '_bibliography/rits-astra.bib'):
    try:
        refresh(destination)
    except RemoteFetchError:
        # Only download() classifies remote errors; local failures remain fatal.
        print('HAL remote fetch unavailable; bibliography not replaced.', file=sys.stderr)
        return REMOTE_FAILURE
    except Exception:
        # Do not print response bodies, credentials, or partially parsed data.
        print('ERROR: HAL update failed locally or produced invalid data; existing bibliography preserved.',
              file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
